version : '3.8'

services:
  mysql:
      image: mysql:5.6
      container_name: mysql
      ports:
        - '3307:3306'
      networks:
        - node_network
      volumes:
        - '~/data-mysql:/var/lib/mysql'
      environment:
        MYSQL_ROOT_PASSWORD: '12345678'

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
        - '8181:80'
      environment:
        PMA_HOST: mysql
      networks:
        - node_network
      depends_on:
        - mysql

  backend-node:
    image: ayiangio/node-docker:latest
    container_name: backend-node
    ports: 
      - '3030:3000'
    environment:
      - NAME= ayi
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=12345678
    networks:
      - node_network
    depends_on:
      - mysql
      - phpmyadmin

networks:
  node_network:
    name: node_network