# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Automation Deployment

on:
  push:
    branches : [cicd]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: garygrossgarten/github-action-scp@release
        with:
          local: nodeDocker/*
          remote: /home/yunandar/ayi/nodeDocker
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm start 